import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    'service-chains',
    'foundations'
  ],
  curriculumSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;